from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class CommentDetail(BaseModel):
    comment_id: str = Field(..., description="Unique comment identifier")
    author: str = Field(..., description="Comment author's name")
    comment_text: str = Field(..., description="Body of the comment")
    generated_reply: Optional[str] = Field(None, description="The reply generated by the bot, if any")
    status: str = Field(..., description="Status of processing: 'replied', 'skipped', or 'failed'")
    reason: Optional[str] = Field(None, description="Reason for skip or failure")
    timestamp: str = Field(..., description="Time of processing")

class ReplyResponse(BaseModel):
    status: str = Field("success", description="Status of the request execution")
    total_comments: int = Field(0, description="Total comments found")
    replied: int = Field(0, description="Total replies posted successfully")
    skipped: int = Field(0, description="Total comments skipped")
    details: Optional[List[CommentDetail]] = Field(None, description="Detailed list of processed comments")
    message: Optional[str] = Field(None, description="Status or error message")

class BotStatusResponse(BaseModel):
    is_running: bool = Field(False, description="Whether the bot is currently running an automation task")
    current_video_id: Optional[str] = Field(None, description="Video ID being processed, if any")
    total_runs: int = Field(0, description="Total runs performed")
    last_run_timestamp: Optional[str] = Field(None, description="Timestamp of the last run completion")
    last_run_statistics: Optional[Dict[str, Any]] = Field(None, description="Statistics from the last automation run")
